{"created": 1754033411.3900669, "duration": 0.4473280906677246, "exitcode": 1, "root": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem", "environment": {}, "summary": {"error": 1, "total": 1, "collected": 30}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "backend/tests/api/test_auth.py", "type": "Module"}, {"nodeid": "backend/tests/api/test_incidents.py", "type": "Module"}]}, {"nodeid": "backend/tests/api/test_auth.py::TestClient", "outcome": "passed", "result": []}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI", "outcome": "passed", "result": [{"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_login_success", "type": "Function", "lineno": 11}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_login_invalid_credentials", "type": "Function", "lineno": 26}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_login_missing_credentials", "type": "Function", "lineno": 39}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_register_success", "type": "Function", "lineno": 46}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_register_duplicate_email", "type": "Function", "lineno": 64}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_register_invalid_email", "type": "Function", "lineno": 73}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_get_current_user", "type": "Function", "lineno": 86}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_get_current_user_unauthorized", "type": "Function", "lineno": 99}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_token_refresh", "type": "Function", "lineno": 106}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_logout", "type": "Function", "lineno": 117}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_change_password", "type": "Function", "lineno": 125}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_change_password_invalid_current", "type": "Function", "lineno": 137}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_forgot_password", "type": "Function", "lineno": 149}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_reset_password", "type": "Function", "lineno": 157}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_verify_token", "type": "Function", "lineno": 170}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_verify_invalid_token", "type": "Function", "lineno": 181}]}, {"nodeid": "backend/tests/api/test_auth.py", "outcome": "passed", "result": [{"nodeid": "backend/tests/api/test_auth.py::TestClient", "type": "Class"}, {"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI", "type": "Class"}]}, {"nodeid": "backend/tests/api/test_incidents.py::TestClient", "outcome": "passed", "result": []}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI", "outcome": "passed", "result": [{"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_get_incidents_list", "type": "Function", "lineno": 12}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_create_incident", "type": "Function", "lineno": 20}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_get_incident_by_id", "type": "Function", "lineno": 32}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_update_incident", "type": "Function", "lineno": 46}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_delete_incident", "type": "Function", "lineno": 61}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_filter_incidents_by_status", "type": "Function", "lineno": 76}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_filter_incidents_by_priority", "type": "Function", "lineno": 85}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_search_incidents", "type": "Function", "lineno": 94}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_assign_incident", "type": "Function", "lineno": 104}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_incident_validation_errors", "type": "Function", "lineno": 118}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_incident_access_requires_auth", "type": "Function", "lineno": 134}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI::test_incident_crud_with_auth", "type": "Function", "lineno": 144}]}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPIAsync", "outcome": "passed", "result": [{"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPIAsync::test_async_get_incidents", "type": "Function", "lineno": 163}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPIAsync::test_async_create_incident", "type": "Function", "lineno": 172}]}, {"nodeid": "backend/tests/api/test_incidents.py", "outcome": "passed", "result": [{"nodeid": "backend/tests/api/test_incidents.py::TestClient", "type": "Class"}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPI", "type": "Class"}, {"nodeid": "backend/tests/api/test_incidents.py::TestIncidentAPIAsync", "type": "Class"}]}], "tests": [{"nodeid": "backend/tests/api/test_auth.py::TestAuthAPI::test_login_success", "lineno": 11, "outcome": "error", "keywords": ["test_login_success", "auth", "api", "pytestmark", "TestAuthAPI", "backend/tests/api/test_auth.py", "ITSM-ITmanagementSystem"], "setup": {"duration": 0.11716480199902435, "outcome": "failed", "crash": {"path": "/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py", "lineno": 56, "message": "TypeError: object Mock can't be used in 'await' expression"}, "traceback": [{"path": "tests/conftest.py", "lineno": 91, "message": "in client"}, {"path": "/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py", "lineno": 745, "message": "in __enter__"}, {"path": "/home/kensan/.local/lib/python3.12/site-packages/anyio/from_thread.py", "lineno": 277, "message": "in call"}, {"path": "/usr/lib/python3.12/concurrent/futures/_base.py", "lineno": 456, "message": "in result"}, {"path": "/usr/lib/python3.12/concurrent/futures/_base.py", "lineno": 401, "message": "in __get_result"}, {"path": "/home/kensan/.local/lib/python3.12/site-packages/anyio/from_thread.py", "lineno": 217, "message": "in _call_func"}, {"path": "/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py", "lineno": 774, "message": "in wait_startup"}, {"path": "/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py", "lineno": 771, "message": "in receive"}, {"path": "/usr/lib/python3.12/concurrent/futures/_base.py", "lineno": 449, "message": "in result"}, {"path": "/usr/lib/python3.12/concurrent/futures/_base.py", "lineno": 401, "message": "in __get_result"}, {"path": "/home/kensan/.local/lib/python3.12/site-packages/anyio/from_thread.py", "lineno": 217, "message": "in _call_func"}, {"path": "/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py", "lineno": 761, "message": "in lifespan"}, {"path": "/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py", "lineno": 56, "message": "in __call__"}], "longrepr": "tests/conftest.py:91: in client\n    with TestClient(app) as test_client:\n/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py:745: in __enter__\n    portal.call(self.wait_startup)\n/home/kensan/.local/lib/python3.12/site-packages/anyio/from_thread.py:277: in call\n    return cast(T_Retval, self.start_task_soon(func, *args).result())\n/usr/lib/python3.12/concurrent/futures/_base.py:456: in result\n    return self.__get_result()\n/usr/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/home/kensan/.local/lib/python3.12/site-packages/anyio/from_thread.py:217: in _call_func\n    retval = await retval\n/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py:774: in wait_startup\n    message = await receive()\n/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py:771: in receive\n    self.task.result()\n/usr/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/usr/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/home/kensan/.local/lib/python3.12/site-packages/anyio/from_thread.py:217: in _call_func\n    retval = await retval\n/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py:761: in lifespan\n    await self.app(scope, self.stream_receive.receive, self.stream_send.send)\n/home/kensan/.local/lib/python3.12/site-packages/starlette/testclient.py:56: in __call__\n    await instance(receive, send)\nE   TypeError: object Mock can't be used in 'await' expression"}, "teardown": {"duration": 0.0023862289999669883, "outcome": "passed"}}], "warnings": [{"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 12}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 13}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 27}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 28}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 40}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 41}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 47}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 48}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 65}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 66}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 74}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 75}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 87}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 88}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 100}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 101}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 107}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 108}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 118}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 119}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 126}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 127}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 138}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 139}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 150}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 151}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 158}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 159}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 171}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 172}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 182}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_auth.py", "lineno": 183}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 13}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 21}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 33}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 47}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 62}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 77}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 86}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 95}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 105}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 119}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 135}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 136}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 145}, {"message": "Unknown pytest.mark.auth - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 146}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 165}, {"message": "Unknown pytest.mark.api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/media/kensan/LinuxHDD/ITSM-ITmanagementSystem/backend/tests/api/test_incidents.py", "lineno": 174}]}